[package]
name = "skyangle"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"
license = "MIT"
description = "Astronomical angles conversion"
repository = "https://github.com/rconan/skyangle"
documentation = "https://docs.rs/skyangle"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]
